local wilson_attack = 34
local TUNING = GLOBAL.TUNING

if GetModConfigData("config_tridentBuff") == 1 then
    TUNING.TRIDENT.DAMAGE = wilson_attack * 1.5
    TUNING.TRIDENT.USES = TUNING.TRIDENT.USES + 50
    TUNING.TRIDENT.SPELL.USE_COUNT = TUNING.TRIDENT.USES
elseif GetModConfigData("config_tridentBuff") == 2 then
    TUNING.TRIDENT.DAMAGE = wilson_attack * 3.0
    TUNING.TRIDENT.USES = TUNING.TRIDENT.USES + 50
    TUNING.TRIDENT.SPELL.USE_COUNT = TUNING.TRIDENT.USES
end

if GetModConfigData("config_easierRockjaws") then
    TUNING.SHARK.DAMAGE = 50 / 3
end

TUNING.MESSAGEBOTTLE_NOTE_CHANCE = GetModConfigData("config_moreTreasure")
TUNING.MODDED_PRESET_TRESHHOLD = GetModConfigData("config_customTreasure")

--beta
TUNING.MONKEYISLANDGEN_DOCKAMOUNT = TUNING.MONKEYISLANDGEN_DOCKAMOUNT*GetModConfigData("config_islandSize")
TUNING.MONKEYISLANDGEN_DOCKMINLENGTH = TUNING.MONKEYISLANDGEN_DOCKMINLENGTH*GetModConfigData("config_islandSize")
TUNING.MONKEYISLANDGEN_DOCKMAXLENGTH = TUNING.MONKEYISLANDGEN_DOCKMAXLENGTH*GetModConfigData("config_islandSize")
TUNING.MONKEYISLANDGEN_CANNONCHANCE = TUNING.MONKEYISLANDGEN_CANNONCHANCE*GetModConfigData("config_islandSize")

TUNING.BOAT.BOATCANNON.POWER = TUNING.BOAT.BOATCANNON.POWER*GetModConfigData("config_cannonPower")

if GetModConfigData("config_battlePaddle") then
    TUNING.BOAT.OARS.MONKEY.FORCE = 0.6
    TUNING.BOAT.OARS.MONKEY.DAMAGE = wilson_attack * 1.25
    TUNING.BOAT.OARS.MONKEY.ROW_FAIL_WEAR = 1
    TUNING.BOAT.OARS.MONKEY.ATTACKWEAR = 1
    TUNING.BOAT.OARS.MONKEY.MAX_VELOCITIY = 4
end

TUNING.BOAT.BUMPERS.KELP.HEALTH = TUNING.BOAT.BUMPERS.KELP.HEALTH*GetModConfigData("config_bumperHealth")
TUNING.BOAT.BUMPERS.SHELL.HEALTH = TUNING.BOAT.BUMPERS.SHELL.HEALTH*GetModConfigData("config_bumperHealth")